name: Bug Report
description: File a bug report.
title: "fix: "
labels: ["fix"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version are you running?
      placeholder: '0.0.0'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: >
        Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: sanity-check
    attributes:
      label: I assert this issue is relevant
      description: |
        By submitting this issue you assert that:
        (1) you agree to follow our Code of Conduct, see CODE_OF_CONDUCT.md for
        more details.
        (2) that you've searched for similar issues and found no issues that
        described the same issues as this one
        (3) This is an actual bug and not a request for support.
        (4) this issue is not about a security venerability. See SECURITY.md
        for more information
      options:
        - label: >
           I assert that I have read the [Code of
           Conduct](https://github.com/Tygo-van-den-Hurk/Slyde/blob/main/CODE_OF_CONDUCT.md)
           and agree to abide by it.
          required: true
        - label: > 
            I assert that this is not a [duplicate of an existing
            issue](https://github.com/Tygo-van-den-Hurk/Slyde/issues?q=label%3A%22fix%22).
          required: true
        - label: >
            I assert that this is a bug and not a support request.
          required: true
        - label: >
            I assert that this is a bug and not a security venerability. See [
            SECURITY.md](https://github.com/Tygo-van-den-Hurk/Slyde/blob/main/SECURITY.md)
            for more information
          required: true
  - type: "markdown"
    attributes:
      value: |
        ### Thank you for filling out this issue!

        ---
  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**
        This template helps developers know which issues should be prioritised
        by allowing users to vote with a :+1: reaction. This is not a guarantee
        that highly-requested issues will be fixed first, but it helps us to
        figure out what's important to users. Please react on other users'
        issues if you find them important.
      value: |
        Add a :+1: [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/Tygo-van-den-Hurk/Slyde/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
