name: Documentation issue
description: Request additions, updates, or improvements to the documentation.
title: "docs: "
labels: ["docs"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to submit a documentation request.
        Please provide clear and concise details to help us address it
        efficiently.
  - type: textarea
    id: request
    attributes:
      label: Documentation issue
      description: >
        Describe what documentation is missing, outdated, or unclear. Include
        any suggested changes if relevant.
      placeholder: Explain the documentation change you would like to see.
    validations:
      required: true
  - type: checkboxes
    id: sanity-check
    attributes:
      label: I assert this issue is relevant
      description: |
        By submitting this issue you assert that:
        (1) you agree to follow our Code of Conduct, see CODE_OF_CONDUCT.md for
        more details.
        (2) that you've searched for similar issues and found no issues that
        described the same issues as this one
      options:
        - label: >
           I assert that I have read the [Code of
           Conduct](https://github.com/Tygo-van-den-Hurk/Slyde/blob/main/CODE_OF_CONDUCT.md)
           and agree to abide by it.
          required: true
        - label: > 
            I assert that this is not a [duplicate of an existing
            issue](https://github.com/Tygo-van-den-Hurk/Slyde/issues?q=label%3A%22docs%22).
          required: true
  - type: "markdown"
    attributes:
      value: |
        ### Thank you for filling out this issue!

        ---
  - type: "textarea"
    id: "prioritisation"
    attributes:
      label: "Is this issue important to you?"
      description: |
        **Please do not modify this text area!**
        This template helps developers know which issues should be prioritised
        by allowing users to vote with a :+1: reaction. This is not a guarantee
        that highly-requested issues will be fixed first, but it helps us to
        figure out what's important to users. Please react on other users'
        issues if you find them important.
      value: |
        Add a :+1: [reaction] to [issues you find important].

        [reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
        [issues you find important]: https://github.com/Tygo-van-den-Hurk/Slyde/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
